/**
 * @file stm32_gps_emulator.c
 * @brief Part 3 – STM32 GPS emulator (C, STM32 HAL).
 *
 * Runs on an STM32 microcontroller. Periodically transmits 160-byte
 * I2C frames to the BeagleBone Green, alternating START and END messages
 * for a table of simulated vehicles.
 *
 * Compile for STM32 target with -DSTM32_TARGET and link against the
 * HAL library generated by STM32CubeMX.  Without that flag the HAL
 * calls are stubbed out so the file can be syntax-checked on Linux.
 *
 * Frame layout (packed, 160 bytes) – must match bbg_i2c.c i2c_frame_t:
 *   [0]      type byte  'S' or 'E'
 *   [1-64]   customer_id (null-terminated)
 *   [65-80]  latitude  as ASCII string
 *   [81-96]  longitude as ASCII string
 *   [97-159] city (null-terminated)
 */

#ifdef STM32_TARGET
#  include "stm32f4xx_hal.h"   /* adjust for your STM32 family */
#else
/* ── Host stubs for syntax checking on Linux ────────────────────────────── */
#  include <stdint.h>
#  include <string.h>
#  include <stdio.h>
#  include <unistd.h>
   typedef struct { uint32_t Instance; } I2C_HandleTypeDef;
   typedef uint32_t HAL_StatusTypeDef;
#  define HAL_OK 0
#  define HAL_I2C_Master_Transmit(h,a,b,s,t) (HAL_OK)
#  define HAL_Delay(ms) usleep((ms)*1000u)
#endif

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "../common/common.h"

/* ── Configuration ──────────────────────────────────────────────────────── */

#define I2C_SLAVE_ADDR    (0x08 << 1) /**< BBG slave address, left-shifted   */
#define I2C_FRAME_BYTES   160
#define I2C_TIMEOUT_MS    1000
#define PARK_DURATION_MS  30000       /**< Simulated parking session length   */
#define CYCLE_DELAY_MS    10000       /**< Pause between vehicle slots        */

/* ── Packed frame struct (must match bbg_i2c.c) ─────────────────────────── */

#pragma pack(push, 1)
typedef struct {
    char type;             /* 'S' or 'E'                    offset   0 */
    char customer_id[64];  /* null-terminated               offset   1 */
    char lat_str[16];      /* ASCII decimal e.g."32.085300" offset  65 */
    char lon_str[16];      /* ASCII decimal e.g."34.781700" offset  81 */
    char city[63];         /* null-terminated               offset  97 */
} i2c_frame_t;             /*                               total  160 */
#pragma pack(pop)

/* ── Simulated vehicle table ────────────────────────────────────────────── */

typedef struct {
    const char *customer_id;
    double      latitude;
    double      longitude;
    const char *city;
} vehicle_t;

static const vehicle_t g_vehicles[] = {
    { "VH-001",  32.0853,  34.7818, "TelAviv"   },
    { "VH-002",  31.7683,  35.2137, "Jerusalem" },
    { "VH-003",  32.7940,  34.9896, "Haifa"     },
    { "VH-004",  31.2518,  34.7913, "BeerSheva" },
};
#define NUM_VEHICLES (sizeof(g_vehicles) / sizeof(g_vehicles[0]))

/* ── HAL I2C handle (declared by CubeMX in the STM32 build) ─────────────── */

#ifdef STM32_TARGET
extern I2C_HandleTypeDef hi2c1;
#else
static I2C_HandleTypeDef hi2c1;
#endif

/* ── Helpers ─────────────────────────────────────────────────────────────── */

/**
 * @brief Fill a frame struct from vehicle data and a type byte.
 * @param frame  Output buffer.
 * @param v      Vehicle entry.
 * @param type   MSG_START ('S') or MSG_END ('E').
 */
static void build_frame(i2c_frame_t *frame,
                        const vehicle_t *v,
                        char type)
{
    memset(frame, 0, sizeof(i2c_frame_t));
    frame->type = type;
    strncpy(frame->customer_id, v->customer_id,
            sizeof(frame->customer_id) - 1);
    snprintf(frame->lat_str, sizeof(frame->lat_str), "%.6f", v->latitude);
    snprintf(frame->lon_str, sizeof(frame->lon_str), "%.6f", v->longitude);
    strncpy(frame->city, v->city, sizeof(frame->city) - 1);
}

/**
 * @brief Transmit one frame to the BBG via I2C.
 * @return 0 on success, -1 on HAL error.
 */
static int send_frame(const i2c_frame_t *frame)
{
    HAL_StatusTypeDef rc = HAL_I2C_Master_Transmit(
        &hi2c1,
        I2C_SLAVE_ADDR,
        (uint8_t *)frame,
        I2C_FRAME_BYTES,
        I2C_TIMEOUT_MS);

    return (rc == HAL_OK) ? 0 : -1;
}

/* ── Entry point ─────────────────────────────────────────────────────────── */

int main(void)
{
#ifdef STM32_TARGET
    HAL_Init();
    SystemClock_Config();   /* generated by CubeMX */
    MX_I2C1_Init();         /* generated by CubeMX */
#endif

    size_t idx = 0;
    i2c_frame_t frame;

    while (1) {
        const vehicle_t *v = &g_vehicles[idx % NUM_VEHICLES];

        /* Send START */
        build_frame(&frame, v, MSG_START);
        if (send_frame(&frame) != 0) {
            HAL_Delay(2000);   /* I2C error – wait and retry */
            continue;
        }

        /* Simulate parking */
        HAL_Delay(PARK_DURATION_MS);

        /* Send END */
        build_frame(&frame, v, MSG_END);
        send_frame(&frame);    /* best-effort */

        HAL_Delay(CYCLE_DELAY_MS);
        idx++;
    }

    return 0; /* never reached on embedded target */
}
